name: Otomasi Deploy Lokal

# Berjalan setelah workflow Kualitas Kode (quality-check) selesai
on:
  workflow_run:
    workflows: ["Kualitas Kode (Quality Check)"]
    types:
      - completed

jobs:
  deploy:
    # Memerintahkan GitHub untuk mencari agen di komputermu
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Menarik kode terbaru dari GitHub
        uses: actions/checkout@v3

      - name: Sinkronisasi Kode ke Folder Project
        run: |
          rsync -av --delete --exclude '.git/' --exclude '.env' --exclude 'node_modules/' --exclude 'nginx/ssl/' ./ /home/vagrant/projectWeb1/

      - name: Eksekusi Docker Compose
        run: |
          cd /home/vagrant/projectWeb1
          docker compose down
          docker compose up --build -d
          
      - name: Kirim Notifikasi Sukses ke Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "👌 DEPLOYMENT: SUCCESS",
                   "description": "Automatic deployment successful, Application has been deployed on local server with active status.",
                   "color": 3066993,
                   "fields": [
                     {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
                     {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
                     {"name": "Commit Message", "value": "'"${{ github.event.workflow_run.head_commit.message || github.event.head_commit.message }}"'", "inline": false}
                   ]
                 }]
               }' \
               https://discord.com/api/webhooks/1481288533833683016/QivZ9fxgg57t_iQjepDOcLS9Zfb84MWxO4XNNQP-9bF_7HcIhzp634uTVwGeUML1TfVK

      - name: Kirim Notifikasi Gagal ke Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "💀 DEPLOYMENT: FAILURE",
                   "description": "Automatic deployment failed! An error occurred while executing Docker Compose.",
                   "color": 15158332,
                   "fields": [
                     {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
                     {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
                     {"name": "Commit Message", "value": "'"${{ github.event.workflow_run.head_commit.message || github.event.head_commit.message }}"'", "inline": false}
                   ]
                 }]
               }' \
               https://discord.com/api/webhooks/1481288533833683016/QivZ9fxgg57t_iQjepDOcLS9Zfb84MWxO4XNNQP-9bF_7HcIhzp634uTVwGeUML1TfVK
