name: Otomasi Deploy Lokal

# Robot bekerja saat ada push ke branch main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Memerintahkan GitHub untuk mencari agen di komputermu
    runs-on: self-hosted

    steps:
      - name: Menarik kode terbaru dari GitHub
        uses: actions/checkout@v3

      - name: Eksekusi Docker Compose
        run: |
          cd /home/vagrant/projectWeb1
          docker compose down
          docker compose up --build -d
          
      - name: Selesai
        run: echo "Deploy otomatis berhasil, Bos Gerardo!"