name: Kualitas Kode (Quality Check)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Menarik kode terbaru dari GitHub
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Jalankan Linter
        run: npm run lint

      - name: Jalankan Unit Test
        run: npm test

      - name: Kirim Notifikasi Sukses ke Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "✅ CODE QUALITY: SUCCESS",
                   "description": "Code quality check passed without any errors, Linting and Unit Test passed.",
                   "color": 3066993,
                   "fields": [
                     {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
                     {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
                     {"name": "Commit Message", "value": "'"${{ github.event.head_commit.message }}"'", "inline": false}
                   ]
                 }]
               }' \
               https://discord.com/api/webhooks/1481288533833683016/QivZ9fxgg57t_iQjepDOcLS9Zfb84MWxO4XNNQP-9bF_7HcIhzp634uTVwGeUML1TfVK

      - name: Kirim Notifikasi Gagal ke Discord
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "❌ CODE QUALITY: FAILED",
                   "description": "Code quality check failed! Linting or Unit Test detected an error.",
                   "color": 15158332,
                   "fields": [
                     {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
                     {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
                     {"name": "Commit Message", "value": "'"${{ github.event.head_commit.message }}"'", "inline": false}
                   ]
                 }]
               }' \
               https://discord.com/api/webhooks/1481288533833683016/QivZ9fxgg57t_iQjepDOcLS9Zfb84MWxO4XNNQP-9bF_7HcIhzp634uTVwGeUML1TfVK
